### ISSUE TITLE
Experiential Edge Cases

### ISSUE THREAD

**Issue by nicschumann** [nicschumann/many-rivers#11]
## Edge Cases & Failure Modes

This simulator and renderer is fairly resource intensive, and probably requires a recent computer with a decent, WebGL capable graphics card to work at all. We should consider what happens when people don't meet that minimum hardware requirement.

### Todos

- [ ] Consider how things work if someone has a slow internet connection
- [ ] Consider how things work if someone has a bad graphics card
- [ ] Consider how things work if someone is on a phone

**Comment by federicoperezvilloro** [comment]
I added a "technical disclaimer" to the info panel. 

Thinking we can design for desktop computers only for now and have a message about it when detecting a user visiting from mobile. 

Regarding slow internet connectivity and graphic cards, is it something we can automatically detect as to trigger messages or should we just list a series of things in the info panel disclaimer?

**Comment by nicschumann** [comment]
We're going with a technical disclaimer for the time being. If we test on a lot of comps and find it's slow, we'll just scale down the resolution of the simulation domain. That's the best way to increase the frame rate of the simulation!

This is closed by #47.
