### ISSUE TITLE
Camera Characters

### ISSUE THREAD

**Issue by nicschumann** [nicschumann/many-rivers#4]
## Camera

Hypothesis: A key "character" in the _Many Rivers_ experience is the first-person camera. We're interested in presenting interactive, and pre-scripted sequences through the 3D (2.5D?) river landscape as a way of exploring the relationship between multiple subjects and the river. **NOTE(Nic):** Discuss w/ Fede.

### Todos

- [x] Develop controllable "Free-look" camera.
- [ ] Develop controllable camera with "interesting," embodied dynamics
- [ ] Develop software-scriptable camera
- [ ] Develop UI-scriptable camera **NOTE(Nic):** Maybe.

**Comment by nicschumann** [comment]
@federicoperezvilloro Let's use this space to discuss the various characters that our first-person camera might assume. I'll leave a brief summary of a few that we talked about during the call:

### First Person View
- We discussed a camera that moves and operates across the model at a human scale, simulating the movement of a persona cross the landscape of the river. 
- The scale of our DEMs is roughly 1 meter per pixel, so think of this character of moving across the world at roughly 1 pixel per second or so, and the camera being placed about 1.8 pixel-heights above the terrain height. 

### Drone View
- We discussed a camera that behaves somewhat like a vulture or a drone, looking down on the surface.
- This camera might circle around the terrain like a buzzard, at a significantly faster surface speed, with an elevation of between 150 pixels and 500 pixels. 
- We'd like the height of this character to be such that you can still discern interesting, 3D features of the land, but that you can also obtain a grand perspective of the river.
- Perhaps you can control the focal length / zoom of the camera, zooming in and out on various aspects of the changing river like a surveillance / drone camera.

### Questions
1. Thoughts on these two characters?
2. Any others you'd like to introduce at the moment?
3. How/when would a viewer transition between these?

**Comment by federicoperezvilloro** [comment]
Yes @nicschumann, I think it makes a lot of sense to script behaviors based on characters / camera POVs. We're telling a story and we can do so at different perspective scales. 

The drone view might be more suited to show large scale geomorphological evolution. While the first person camera might make the experience more embodied and allow for other river manifestations to become apparent, such as water sound and other subtle interactions. 

I woudn’t consider any other characters at this point. Seems like the contrast between these two might be nice. 

The question on how to transition perspectives is a good one. Are these characters actually different characters? Do they exist in different spatial positions simultaneously and, if so, how literal do we want that to be. For instance if a user is looking at the sky from the ground view, do they see a flying vulture circling above them? My intuition is that they don't and to make these characters more abstract and not as illustrative... 

Maybe the drone view is how scenes/locations get introduced to user. It allows less control over the camera movement — just subtle inclinations and so on. From there users could point to a place on the ground and get there with some interface command. 

We could also make the experience a bit less idiosyncratic and just have a way to toggle back and forth from ground to drone view protecting the placement of the camera to where it is when a toggle is activated. If the drone is flying in circles it might get a bit distanced from the actual course of the river. Do we want to limit that somehow?

**Comment by nicschumann** [comment]
This is superseded by:

- #18 
- #17 
- #16
