### ISSUE TITLE
DEM Processing

### ISSUE THREAD

**Issue by nicschumann** [nicschumann/many-rivers#5]
## DEMs

We're interested in using "real" DEMs of 6 different locations along the Rio Grande from Juárez to Matamoros – as indicated in [this map](https://www.google.com/maps/d/u/1/viewer?mid=1QlgXngNVkikH1h254YM8S-2BiVKiud0&ll=28.72317481792406%2C-101.8625957&z=7), and in the screenshot below.

<img width="858" alt="juarez-matamoros" src="https://github.com/nicschumann/many-rivers/assets/4285161/6d69fb0d-824e-4c20-b91a-2a2a8317885a">

### Todos

- [x] ~Consider whether it makes sense to hire someone for DEM postprocessing.~
- [x] Work with Lukas to obtain DEM data for the 6 locations along the Rio Grande.
- [x] Clean up and de-noise DEM data to obtain working inputs.
- [x] Add de-noising and cleanup scripts and process to this repository.
- [x] Test simulator with real DEMs to define parameter operating ranges.

**Comment by nicschumann** [comment]
Sent an email out to Lukas about getting GIS exports for the 6 locations above. I will keep this thread updated with progress in obtaining high-resolution, 5km x 5km at 1 meter / pixel scale DEMs.

**Comment by federicoperezvilloro** [comment]
@nicschumann I saw Lukas email about the DEM's at the locations we specified being one-sided. I wonder if the one near Matamoros incorporates both sides of the river given the tight meandering of the river. With that in mind marked a few other similar locations to search for DEMs in this map: https://www.google.com/maps/d/u/0/edit?mid=1CCYS0Dn_6M2PsTqoLxEdDcTKyhvxUII&usp=sharing

**Comment by nicschumann** [comment]
Lukas linked to the [USGS Lidar Explorer](https://apps.nationalmap.gov/lidar-explorer/#/) here (I didn't know about this link)! If you zoom around this map, you can clearly see which areas have LIDAR on both sides available.

Your theory is definitely a good one; the cross-border scan data must have been removed from the dataset. Maybe for political reasons? Either way, it's interesting.

It looks like there is some cross-border scan data available, primarily in the reach where the Rio Grande flushes into the Gulf of Mexico, from a little upstream of Reynosa through Matamoros, and to the sea. It doesn't look like there are any regions further upstream than a bit west of Reynosa. 

![Image](https://github.com/nicschumann/many-rivers/assets/4285161/f49e36bf-0470-4d4c-88e0-10de99e1c52d)

_In the image, the darker green is where 1-meter DEM data exists; the lighter green is where LIDAR data exists._

Big question: How do we feel about restricting our sites to these areas closer to the gulf? I think it's unlikely that we'll find a better dataset than USGS. The next best might be MapBox, but those are 5-meter DEMs, and we'd loose significant resolution.

**Comment by federicoperezvilloro** [comment]
That is great to know that there is need cross border data. Yes, totally fine to focus on the areas closer to the gulf. 

With that in mind, is it possible to stitch together the whole line across a larger trajectory? As to make one longer "scene" as supposed to a series of them. Let's say from Reynosa/Matamoros to the ocean?

We could also select a few interesting geometries in such region. Maybe those with deep curbs similar to the one near Matamoros... I will mark more on the link I shared on my previous message. 

Or should we base our selection on the quality on the models?

**Comment by nicschumann** [comment]
I think it depends on how much manual cleanup I need to do of this data. If I can automate the cleanup, we can try and stitch together a longer reach, but if it's mostly manual, we'll need to select a few vignettes (deep curves, if you like) to focus on. I'll work through some scenarios and let you know.

**Comment by nicschumann** [comment]
## Candidate DEMs

> This list will be updated by Nic as he pulls areas new DEMs from the USGS database

- [South TX, B8](https://www.sciencebase.gov/catalog/item/5eacfdaa82cefae35a2515f8), tif offset | `x: 5500 y: 6500 h: 1800, w: 1800`

**Comment by nicschumann** [comment]
Hey @federicoperezvilloro, I've identified seven areas along the gulf reach of the river (based on the map you shared). Stitching together a continuous string of river segments is going to be too much work at this moment – each of the DEMs requires some amount of manual post-processing. If we truly wanted to stitch them together into a continuous reach in the simulator, as well, that would require some significant re-architecting of the sim method as well, and would reduce the quality of the sim to do our computational budget per frame – a huge lift that feels out of scope to me.

Let's stick to the original plan.

**Comment by nicschumann** [comment]
@federicoperezvilloro – let's consider one more round of possible locations to look at. Can you put together a map of some final locations to test? I'll extract them, and post images here.

**Comment by federicoperezvilloro** [comment]
@nicschumann I added a few more points of interest to our map. I selected locations based on their story telling potential but also on their geological / infraestructural formal qualities. Take a look: https://www.google.com/maps/d/u/0/edit?mid=1CCYS0Dn_6M2PsTqoLxEdDcTKyhvxUII&usp=sharing

Here's a list with the new locations, some with notes/links to hint to why I find them interesting.

Point 10: Rio Rico
https://www.youtube.com/watch?v=nNvDbeliO_0&feature=youtu.be

Point 11: Falcon reservoir 

Point 12: Paya Bagdad
Mirador space X / interaction with sea 

Point 13: Los indios 
Border crossing with bridge

Point 14: Las adjuntas
Intersection btw Rio Bravo and Río San Juan

Point 15: Near Ciudad Mier
Water channeling  

Point 16: Ox bow lake
Brand Christian Youth Camp

Point 17: Laguna la escondida

Point 18: Dona bridge 
Bridge within river's meander

Point 19: Mercedes District Settling Basin
Water reservoir in the US

Point 20: Space X testing facility
https://www.youtube.com/watch?v=kQz3m7te6vY

Point 21: Roma
Popular crossing for undocumented migrants 
https://www.dailymail.co.uk/news/article-9408195/Inside-Roma-small-Texas-border-town-epicenter-illegal-crossings.html

Point 22
Brownsville police department 
https://atlasofsurveillance.org/search?agency=Brownsville+Police+Department

Point 23
Roma police department

**Comment by nicschumann** [comment]
Thank you! Just a note: I may skip some of the ones that are very close to the gulf. I don't think there's enough meaningful elevation change to be captured in a lidar DEM. Will take a peek and see if any look workable, though.

**Comment by nicschumann** [comment]
This is essentially done. We can refer back to this issue as needed, but the list of DEMs is more easily seen in the source code at this stage.
