### ISSUE TITLE
Web Narrative

### ISSUE THREAD

**Issue by nicschumann** [nicschumann/many-rivers#8]
## Web Narrative

We know that we want this simulator to live and be accessible on-line, as well as in it's various site-specific gallery instances. To achieve this, we need to design an interaction narrative for the project which answers the following questions:

1. How are people introduced to the world of _Many Rivers_ via the site?
2. How do people navigate the site? What roles do they inhabit and what do they have control over?
3. What, if anything, persists from site-visit to site-visit?
4. What is the information architecture of the site? What needs to be included? Are there any subpages? Persistent navigation?
5. How much money do we have to maintain the site over time?

### Todos

- [x] Sketch out screens: how does the site present the rendering to its visitors?
- [x] Sketch out a typical visitor journey: someone lands on the site, then what happens? how do they interact, and when do they leave?
- [x] Sketch out an extremely long visitor journey: If someone really gets immersed, how are they likely to move through the site.
- [x] Sketch out a very short visitor journey: What happens if someone only spends a very short time with us?
- [x] Consider persistence: are any parts of a user's journey saved? Is it possible for people to "see each other's footprints" in some sense?

**Comment by nicschumann** [comment]
## Notes from Fede:
- Imagined Journey:
  - You enter the website at a random location.
  - The space is open for exploration
  - Hopefully you see the river evolve in time.
  - **Tradeoff:** There is an interesting trade-off: You can set the time step `dt` to whatever you want... but, the larger it steps – the farther you look into the future – the less accurate, more chaotic it becomes.
  - If theres a way to mess with time, that's a measure that's legible to people. Changing water levels, changing water speeds.
- Web experience should be complex enough for people to engage with the simulator, but
- Should also be legible enough for people to figure to understand.
- How do we communicate the river changing to the viewer? How can we provoke that to become legible in a shorter experience?

#### Maybe a few "characters" to consider the camera inhabiting?
- **First Person Perspective** What would it be like to be really low down on the ground? Would it be too blocky?
- **Drone View?** Maybe we have a fixed, looping trajectory – but is it possible to add some 3D-ness to that?

#### Sounds – this feels critical to generating a sense of place?
- Can you hear footsteps?
- Can you the river?

#### Moving between rivers?
- Is it a choice, or a journey you're taken on? Maybe this depends on the level of control you have? If you don't have access to the simulator, maybe you should be able to move around the system.
- Is it an experience that rewards exploration in some way, or is it a contemplative experience? Right now, thinking of it as a more contemplative experience.

####  The Archive (#9)
- It would be really interesting to archive the river – but if we do that, we should think about that as difference – if people are taking snapshots, how do we make them different enough?
- How big can the archive get? How do we decide whether a river is registered? Can the user decide this?
- We should decide whether the archive is really needed, since the notion of _Many Rivers_ is already coded into the project.

####  Multi-user
- Is it interesting for people to see how other people have interacted with the river over time? There's something interesting about making the river a social space. 
- Could the river start where other people left it?
- Maybe you can see footsteps? Desire lines?

**Comment by federicoperezvilloro** [comment]
@nicschumann I’ve been thinking about the paradoxical relationship between time and the fidelity of the simulator’s outcomes. There is something really interesting there. The further you ask the simulator to move forward in time the less accurate the results will be. The simulator is developed to simulate interactions that might take place across time — you need to let the program run in order to see what happens. So the further away in time, the less trustworthy the results would be. But also, maybe, the most unexpected, visually striking? We should aim towards that sweet spot between the model projecting realizable versions of the river but also going beyond what would be physically possible. The measure to anticipate such levels of realizability being attached to time seems very compelling to me.

**Comment by federicoperezvilloro** [comment]
@nicschumann I took a quick pass on a wire-frame. It could certainly be more detailed but I hope it serves to get our conversation going. Let me know what you think and if we should try to talk soon. 

[wire-frame_1.pdf](https://github.com/nicschumann/many-rivers/files/12207605/wire-frame_1.pdf)

**Comment by nicschumann** [comment]
We've figured out the basic behaviors – more specific things will be catalogued in subsequent issues.
